name: Static Analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress
